#!/bin/sh

branch=$(git symbolic-ref --quiet --short HEAD) || exit 0
remote=$(git config "branch.$branch.remote") || exit 0
upstream=$(git config "branch.$branch.merge") || exit 0

[ -n "$remote" ] || exit 0
[ -n "$upstream" ] || exit 0

git push "$remote" "$branch"
