export default [
	{ path: '/barber/dashboard', name: 'barber-dashboard', component: () => import('./pages/DashboardPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/schedule', name: 'barber-schedule', component: () => import('./pages/SchedulePage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/appointments', name: 'barber-appointments', component: () => import('./pages/AppointmentsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/walk-in', name: 'barber-walk-in', component: () => import('./pages/WalkInPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/profile', name: 'barber-profile', component: () => import('./pages/ProfilePage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/payments', name: 'barber-payments', component: () => import('./pages/PaymentVerificationPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/payments/:id/receipt', name: 'barber-receipt-details', component: () => import('./pages/ReceiptDetailsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services', name: 'barber-services', component: () => import('./pages/ServicesManagementPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services/new', name: 'barber-service-new', component: () => import('./pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services/:id/edit', name: 'barber-service-edit', component: () => import('./pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/gallery', name: 'barber-gallery', component: () => import('./pages/GalleryManagementPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog', name: 'barber-blog', component: () => import('./pages/BlogManagementPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog/new', name: 'barber-blog-new', component: () => import('./pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog/:id/edit', name: 'barber-blog-edit', component: () => import('./pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/notifications', name: 'barber-notifications', component: () => import('./pages/NotificationsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/analytics', name: 'barber-analytics', component: () => import('./pages/AnalyticsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
];