import client from '../../../core/api/axios';

export const customerApi = {
  dashboard: () => client.get('/customer/dashboard'),
  bookings: () => client.get('/customer/bookings'),
  createBooking: (data) => client.post('/customer/bookings', data),
  appointments: () => client.get('/customer/appointments'),
  myCodes: () => client.get('/customer/my-codes'),
  booking: (id) => client.get(`/customer/bookings/${id}`),
  cancelBooking: (id) => client.patch(`/customer/bookings/${id}/cancel`),
  cancelAppointment: (id) => client.patch(`/customer/appointments/${id}/cancel`),
  deleteBooking: (id) => client.delete(`/customer/bookings/${id}`),
  profile: () => client.get('/customer/profile'),
  updateProfile: (data) => client.post('/customer/profile', data, { headers: { 'Content-Type': 'multipart/form-data' } }),
  reviews: () => client.get('/customer/reviews'),
  createReview: (data) => client.post('/customer/testimonials', data),
  getWishlist: () => client.get('/customer/wishlist'),
  addToWishlist: (data) => client.post('/customer/wishlist', data),
  removeFromWishlist: (id) => client.delete(`/customer/wishlist/${id}`),
  removeFromWishlistByType: (type, id) => client.delete(`/customer/wishlist/item?type=${type}&id=${id}`),
  checkout: (data) => client.post('/customer/checkout', data),
  getPaymentDetails: (id) => client.get(`/customer/checkout/${id}/payment-details`),
  uploadReceipt: (id, formData) => client.post(`/customer/checkout/${id}/receipt`, formData, { headers: { 'Content-Type': 'multipart/form-data' } }),
  reactToBlogPost: (id, type) => client.post(`/customer/blog/${id}/react`, { type }),
  removeReactionFromBlogPost: (id) => client.delete(`/customer/blog/${id}/react`),
  notifications: () => client.get('/customer/notifications'),
  updateNotificationSettings: (data) => client.post('/customer/notification-settings', data),
  analytics: (range) => client.get('/customer/analytics', { params: { range } }),
};