export default [
	{ path: '/barber/dashboard', name: 'barber-dashboard', component: () => import('../../features/barber/pages/BarberDashboardPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/schedule', name: 'barber-schedule', component: () => import('../../modules/barber/pages/SchedulePage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/appointments', name: 'barber-appointments', component: () => import('@/features/appointments/pages/BarberAppointmentsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/walk-in', name: 'barber-walk-in', component: () => import('../../modules/barber/pages/WalkInPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/profile', name: 'barber-profile', component: () => import('../../modules/barber/pages/ProfilePage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/payments', name: 'barber-payments', component: () => import('../../modules/barber/pages/PaymentVerificationPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/payments/:id/receipt', name: 'barber-receipt-details', component: () => import('../../modules/barber/pages/ReceiptDetailsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services', name: 'barber-services', component: () => import('../../modules/barber/pages/ServicesManagementPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services/new', name: 'barber-service-new', component: () => import('@/features/services/pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/services/:id/edit', name: 'barber-service-edit', component: () => import('@/features/services/pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/gallery', name: 'barber-gallery', component: () => import('../../features/gallery/pages/BarberGalleryPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog', name: 'barber-blog', component: () => import('../../modules/barber/pages/BlogManagementPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog/new', name: 'barber-blog-new', component: () => import('../../modules/barber/pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/blog/:id/edit', name: 'barber-blog-edit', component: () => import('../../modules/barber/pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/notifications', name: 'barber-notifications', component: () => import('../../modules/barber/pages/NotificationsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/analytics', name: 'barber-analytics', component: () => import('@/features/analytics/pages/BarberAnalyticsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
	{ path: '/barber/reports', name: 'barber-reports', component: () => import('@/features/analytics/pages/BarberReportsPage.vue'), meta: { requiresAuth: true, roles: ['barber'] } },
];