export default [
	{ path: '/admin/dashboard', name: 'admin-dashboard', component: () => import('./pages/DashboardPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/appointments', name: 'admin-appointments', component: () => import('./pages/AppointmentsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/walk-in', name: 'admin-walk-in', component: () => import('./pages/WalkInPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers', name: 'admin-barbers', component: () => import('./pages/BarbersPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers/new', name: 'admin-barber-new', component: () => import('./pages/BarberFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers/:id/edit', name: 'admin-barber-edit', component: () => import('./pages/BarberFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/customers', name: 'admin-customers', component: () => import('./pages/CustomersPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/services', name: 'admin-services', component: () => import('./pages/ServicesPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/services/new', name: 'admin-service-new', component: () => import('./pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/services/:id/edit', name: 'admin-service-edit', component: () => import('./pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/gallery', name: 'admin-gallery', component: () => import('./pages/GalleryPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/testimonials', name: 'admin-testimonials', component: () => import('./pages/TestimonialsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog', name: 'admin-blog', component: () => import('./pages/BlogPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog/new', name: 'admin-blog-new', component: () => import('./pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog/:id/edit', name: 'admin-blog-edit', component: () => import('./pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/working-hours', name: 'admin-working-hours', component: () => import('./pages/WorkingHoursPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/reports', name: 'admin-reports', component: () => import('./pages/ReportsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/analytics', name: 'admin-analytics', component: () => import('./pages/AnalyticsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{
		path: '/admin/websites',
		component: () => import('./layouts/CmsLayout.vue'),
		meta: { requiresAuth: true, roles: ['admin', 'super_admin'] },
		children: [
			{ path: '', redirect: '/admin/websites/home' },
			{ path: 'home', name: 'admin-cms-home', component: () => import('./pages/cms/HomePage.vue') },
			{ path: 'about', name: 'admin-cms-about', component: () => import('./pages/cms/AboutPage.vue') },
			{ path: 'services', name: 'admin-cms-services', component: () => import('./pages/cms/ServicesPage.vue') },
			{ path: 'gallery', name: 'admin-cms-gallery', component: () => import('./pages/cms/GalleryPage.vue') },
			{ path: 'contact', name: 'admin-cms-contact', component: () => import('./pages/cms/ContactPage.vue') },
			{ path: 'privacy', name: 'admin-cms-privacy', component: () => import('./pages/cms/PrivacyPage.vue') },
			{ path: 'terms', name: 'admin-cms-terms', component: () => import('./pages/cms/TermsPage.vue') },
		]
	},
	{ path: '/admin/system-logs', name: 'admin-system-logs', component: () => import('./pages/SystemLogsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/verifications', name: 'admin-verifications', component: () => import('./pages/VerificationPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/notifications', name: 'admin-notifications', component: () => import('./pages/NotificationsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
];