import client from '@/shared/api/client';

export const adminApi = {
  dashboard: () => client.get('/admin/dashboard'),
  appointments: () => client.get('/admin/appointments'),
  approveAppointment: (id) => client.patch(`/admin/appointments/${id}/approve`),
  forceApproveAppointment: (id) => client.patch(`/admin/appointments/${id}/force-approve`),
  cancelAppointment: (id) => client.patch(`/admin/appointments/${id}/cancel`),
  createWalkIn: (data) => client.post('/admin/appointments/walk-in', data),
  services: () => client.get('/services'),
  createService: (data) => client.post('/services', data),
  updateService: (id, data) => client.put(`/services/${id}`, data),
  deleteService: (id) => client.delete(`/services/${id}`),
  serviceCategories: () => client.get('/service-categories'),
  gallery: () => client.get('/admin/gallery'),
  addGalleryImage: (data) => client.post('/admin/gallery', data, { headers: { 'Content-Type': 'multipart/form-data' } }),
  updateGalleryImage: (id, data) => client.post(`/admin/gallery/${id}`, data, { headers: { 'Content-Type': 'multipart/form-data' } }),
  deleteGalleryImage: (id) => client.delete(`/admin/gallery/${id}`),
  testimonials: () => client.get('/admin/testimonials'),
  approveTestimonial: (id) => client.put(`/admin/testimonials/${id}`, { is_approved: true }),
  featureTestimonial: (id) => client.patch(`/admin/testimonials/${id}/feature`),
  deleteTestimonial: (id) => client.delete(`/admin/testimonials/${id}`),
  blogPosts: () => client.get('/admin/blog'),
  createBlogPost: (data) => client.post('/admin/blog', data),
  updateBlogPost: (id, data) => client.post(`/admin/blog/${id}`, data),
  deleteBlogPost: (id) => client.delete(`/admin/blog/${id}`),
  workingHours: () => client.get('/admin/working-hours'),
  updateWorkingHours: (barberId, hours) => client.put(`/admin/working-hours/${barberId}`, { hours }),
  reports: () => client.get('/admin/reports'),
  settings: () => client.get('/admin/settings'),
  updateSettings: (data) => client.post('/admin/settings', data),
  testEmail: (to) => client.post('/admin/test-email', { to }),
  barbers: () => client.get('/admin/barbers'),
  createBarber: (data) => client.post('/admin/barbers', data),
  updateBarber: (id, data) => client.put(`/admin/barbers/${id}`, data),
  updateBarberStatus: (id, status) => client.patch(`/admin/barbers/${id}/status`, { status }),
  deleteBarber: (id) => client.delete(`/admin/barbers/${id}`),
  logs: () => client.get('/admin/logs'),
  customers: () => client.get('/admin/customers'),
  customerProfile: (id) => client.get(`/admin/customers/${id}`),
  analytics: (range) => client.get('/admin/analytics', { params: { range } }),
  verifications: (params) => client.get('/admin/verifications', { params }),
  verifyAppointment: (id) => client.patch(`/admin/verifications/${id}/verify`),
  verificationStats: () => client.get('/admin/verifications/stats'),
  gateMetrics: () => client.get('/admin/gate/metrics'),
  gateLogs: (params) => client.get('/admin/gate/logs', { params }),
  flushGate: (data) => client.post('/admin/gate/flush', data),

  // ── App Management ──
  appOverview: () => client.get('/admin/app/overview'),
  appVersions: () => client.get('/admin/app/versions'),
  storeAppVersion: (data) => client.post('/admin/app/versions', data),
  appSessions: (params) => client.get('/admin/app/sessions', { params }),
  revokeSession: (id) => client.delete(`/admin/app/sessions/${id}`),
  revokeUserSessions: (userId) => client.delete(`/admin/app/sessions/user/${userId}`),
  pushHealth: () => client.get('/admin/app/push-health'),
  pushTest: (data) => client.post('/admin/app/push-test', data),
  appCrashes: (params) => client.get('/admin/app/crashes', { params }),
  resolveCrash: (id) => client.patch(`/admin/app/crashes/${id}/resolve`),
  toggleMaintenance: (data) => client.post('/admin/app/maintenance', data),

  // ── Feature Flags ──
  featureFlags: () => client.get('/admin/feature-flags'),
  createFeatureFlag: (data) => client.post('/admin/feature-flags', data),
  updateFeatureFlag: (id, data) => client.put(`/admin/feature-flags/${id}`, data),
  toggleFeatureFlag: (id) => client.patch(`/admin/feature-flags/${id}/toggle`),
  deleteFeatureFlag: (id) => client.delete(`/admin/feature-flags/${id}`),
};
