export default [
	{ path: '/admin/dashboard', name: 'admin-dashboard', component: () => import('../../modules/admin/pages/DashboardPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/appointments', name: 'admin-appointments', component: () => import('@/features/appointments/pages/AdminAppointmentsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/walk-in', name: 'admin-walk-in', component: () => import('../../modules/admin/pages/WalkInPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers', name: 'admin-barbers', component: () => import('../../modules/admin/pages/BarbersPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers/new', name: 'admin-barber-new', component: () => import('@/features/barbers/pages/BarberFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/barbers/:id/edit', name: 'admin-barber-edit', component: () => import('@/features/barbers/pages/BarberFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/customers', name: 'admin-customers', component: () => import('@/features/customers/pages/CustomersPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'], title: 'Customers' } },
	{ path: '/admin/services', name: 'admin-services', component: () => import('../../modules/admin/pages/ServicesPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/services/new', name: 'admin-service-new', component: () => import('@/features/services/pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/services/:id/edit', name: 'admin-service-edit', component: () => import('@/features/services/pages/ServiceFormPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/gallery', name: 'admin-gallery', component: () => import('../../features/gallery/pages/AdminGalleryPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/testimonials', name: 'admin-testimonials', component: () => import('../../modules/admin/pages/TestimonialsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog', name: 'admin-blog', component: () => import('../../modules/admin/pages/BlogPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog/new', name: 'admin-blog-new', component: () => import('../../modules/admin/pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/blog/:id/edit', name: 'admin-blog-edit', component: () => import('../../modules/admin/pages/BlogEditorPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/working-hours', name: 'admin-working-hours', component: () => import('../../modules/admin/pages/WorkingHoursPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/integrations', name: 'admin-integrations', component: () => import('../../modules/admin/pages/IntegrationsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/api', name: 'admin-api', component: () => import('../../modules/admin/pages/ApiReferencePage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/analytics', name: 'admin-analytics', component: () => import('@/features/analytics/pages/AdminAnalyticsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/settings', name: 'admin-settings', component: () => import('../../modules/superadmin/pages/SettingsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/reports', name: 'admin-reports', component: () => import('@/features/analytics/pages/AdminReportsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{
		path: '/admin/websites',
		name: 'admin-websites',
		component: () => import('./layouts/CmsLayout.vue'),
		meta: { requiresAuth: true, roles: ['admin', 'super_admin'] },
		children: [
			{ path: '', redirect: '/admin/websites/home' },
			{ path: 'home', name: 'admin-cms-home', component: () => import('../../features/cms/pages/HomePage.vue') },
			{ path: 'about', name: 'admin-cms-about', component: () => import('../../modules/admin/pages/cms/AboutPage.vue') },
			{ path: 'services', name: 'admin-cms-services', component: () => import('../../modules/admin/pages/cms/ServicesPage.vue') },
			{ path: 'gallery', name: 'admin-cms-gallery', component: () => import('../../modules/admin/pages/cms/GalleryPage.vue') },
			{ path: 'contact', name: 'admin-cms-contact', component: () => import('../../modules/admin/pages/cms/ContactPage.vue') },
			{ path: 'privacy', name: 'admin-cms-privacy', component: () => import('../../modules/admin/pages/cms/PrivacyPage.vue') },
			{ path: 'terms', name: 'admin-cms-terms', component: () => import('../../modules/admin/pages/cms/TermsPage.vue') },
		]
	},
	{ path: '/admin/system-logs', name: 'admin-system-logs', component: () => import('../../modules/admin/pages/SystemLogsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/verifications', name: 'admin-verifications', component: () => import('@/features/verification/pages/AdminVerificationPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
	{ path: '/admin/notifications', name: 'admin-notifications', component: () => import('../../modules/admin/pages/NotificationsPage.vue'), meta: { requiresAuth: true, roles: ['admin', 'super_admin'] } },
];