export default [
  { path: '/customer/dashboard', name: 'customer-dashboard', component: () => import('../../modules/customer/pages/DashboardPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/bookings', name: 'customer-bookings', component: () => import('../../modules/customer/pages/BookingsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/my-codes', name: 'customer-my-codes', component: () => import('../../modules/customer/pages/MyCodesPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/profile', name: 'customer-profile', component: () => import('../../modules/customer/pages/ProfilePage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/reviews', name: 'customer-reviews', component: () => import('../../modules/customer/pages/ReviewsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/services', name: 'customer-services', component: () => import('../../modules/customer/pages/BrowseServicesPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/services/:id', name: 'customer-service-details', component: () => import('../../modules/customer/pages/ServiceDetailsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/book/:serviceId', name: 'customer-book-service', component: () => import('../../modules/customer/pages/BookServicePage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/wishlist', name: 'customer-wishlist', component: () => import('../../modules/customer/pages/WishlistPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/gallery', name: 'customer-gallery', component: () => import('../../modules/customer/pages/GalleryPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/blog', name: 'customer-blog', component: () => import('../../modules/customer/pages/BlogPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/blog/:slug', name: 'customer-blog-post', component: () => import('../../modules/customer/pages/BlogPostPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },

  { path: '/customer/dashboard/notifications', name: 'customer-notifications', component: () => import('../../modules/customer/pages/NotificationsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/notification-settings', name: 'customer-notification-settings', component: () => import('../../modules/customer/pages/NotificationSettingsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/analytics', name: 'customer-analytics', component: () => import('@/features/analytics/pages/CustomerAnalyticsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/reports', name: 'customer-reports', component: () => import('../../modules/customer/pages/ReportsPage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
  { path: '/customer/dashboard/barber/:id', name: 'customer-barber-profile', component: () => import('../../modules/customer/pages/BarberProfilePage.vue'), meta: { requiresAuth: true, roles: ['customer'] } },
];